# GCP App Engine Flex — uses the Dockerfile directly (required for Bun runtime).
# For GCP Cloud Run:  gcloud run deploy --source .
# For Azure Container Apps: az containerapp up --source .
runtime: custom
env: flex

env_variables:
  NODE_ENV: "production"

resources:
  cpu: 1
  memory_gb: 0.5

automatic_scaling:
  min_num_instances: 0
  max_num_instances: 10
