# GCP App Engine standard environment
runtime: nodejs20

env_variables:
  NODE_ENV: "production"

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 0
  max_instances: 10
